### ISSUE TITLE
Slight edit to step 6 of the installation instructions

### ISSUE THREAD

**Issue by danrubin** [cmod/craigstarter#5]
The added media queries seem to bork things if placed at the start of the Liquid file or various places within it (discovered while helping a non-CSS-familiar friend debug their Craigstarter setup). Suggest adding a few words to step 6 of the install instructions to specify adding the lines to the end of the file for clarity:

6. Add the following CSS to the end of`assets/theme.scss.liquid`:

**Comment by cmod** [comment]
Good tip. Edited! Thanks <3
